'use client'

import Footer from '@components/Footer'
import Navbar from '@components/Navbar'
import '@styles/globals.css'
import { Inter } from 'next/font/google'
import { useRouter } from 'next/navigation'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Atria clone',
  description: 'Generated by Jecy Jehu',
}

const RootLayout = ({ children }) => {
  const router = useRouter()

  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar router={router} />
        {children}
        <Footer router={router} />     
      </body>
    </html>
  )
}

export default RootLayout








// import Footer from '@components/Footer'
// import Navbar from '@components/Navbar'
// import '@styles/globals.css'
// import { Inter } from 'next/font/google'

// const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Atria clone',
//   description: 'Generated by Jecy Jehu',
// }



// const RootLayout = ({children}) => {
//   return (
//     <html lang="en">
//       <body className={inter.className}>
//         <Navbar />
//         {children}
//         <Footer />     
//       </body>
//     </html>
//   )
// }

// export default RootLayout;