import Footer from '@components/Footer'
import Navbar from '@components/Navbar'
import '@styles/globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Atria clone',
  description: 'Generated by Jecy Jehu',
}



const RootLayout = ({children}) => {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        {children}
        <Footer />     
      </body>
    </html>
  )
}

export default RootLayout;