// 'use client'

// import Footer from '@components/Footer'
// import Navbar from '@components/Navbar'
// import '@styles/globals.css'
// import { Inter } from 'next/font/google'
// // import { gsap } from 'gsap-trial/dist/gsap'
// import { gsap } from 'gsap/all'
// import { useRef } from 'react'
// import { usePathname } from 'next/navigation';
// import { ScrollSmoother } from 'gsap/all'
// import { ScrollTrigger } from 'gsap/all'
// // import { ScrollSmoother } from 'gsap-trial/ScrollSmoother'
// // import { ScrollSmoother } from 'gsap-trial/dist/ScrollSmoother'
// // import { ScrollTrigger } from 'gsap-trial/dist/ScrollTrigger'
// import useIsomorphicLayoutEffect from '@helpers/isomorphicEffect'

// gsap.registerPlugin(ScrollTrigger, ScrollSmoother);

// const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Atria clone',
//   description: 'Generated by Jecy Jehu',
// }

// const RootLayout = ({children}) => {
//   const smoother = useRef();
//   const ctx = useRef();
//   const pathname = usePathname();

//   useIsomorphicLayoutEffect(() => {
//     ctx.current = gsap.context(() => {
//       smoother.current = ScrollSmoother.create({
//         smooth: 2,
//         effects: true,
//       });
//     });

//     return () => ctx.current.revert();
//   }, [pathname]);


//   return (
//     <html lang="en">
//       <body className={inter.className}>
//         <Navbar />
//         <section id="smooth-wrapper">
//           <div id='smooth-content'>
//             {children}
//             <Footer />
//           </div>
//         </section>        
//       </body>
//     </html>
//   )
// }

// export default RootLayout;



import Footer from '@components/Footer'
import Navbar from '@components/Navbar'
import '@styles/globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Atria clone',
  description: 'Generated by Jecy Jehu',
}



const RootLayout = ({children}) => {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        {children}
        <Footer />     
      </body>
    </html>
  )
}

export default RootLayout;